server:
  port: 1148

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/quiz
    username: spring_student    #usernmae and password should match as user in sql
    password: springboot

  jpa:
    hibernate:
      ddl-auto: update
